// TODO: Moquei os números aqui enquanto não temos os trem no banco
export const EMAIL = 900
export const NAME = 901
export const DATE_OF_BIRTH = 902
export const PERSONAL_DOCUMENT = 903
export const PERSONAL_EMAIL = 904
export const TELEPHONE = 905
export const DRIVER_LICENSE_NUMBER = 906
export const DRIVER_LICENSE_EXPIRY_DATE = 907
export const PREFERENCE_CITY = 908
export const VEHICLE_TYPE = 909
export const VEHICLE_BRAND = 910
export const VEHICLE_MODEL = 911
export const VEHICLE_PLATE = 912
export const VEHICLE_MODEL_YEAR = 913
export const VEHICLE_FABRICATION_YEAR = 914
export const VEHICLE_IDENTIFICATION_NUMBER = 915
export const VEHICLE_NATIONAL_REGISTRATION_NUMBER = 916
export const VEHICLE_DOCUMENT = 917
export const VEHICLE_LAST_LICENCE_YEAR = 918
export const VEHICLE_OWNERSHIP = 919
export const BANK_HOLDER_NAME = 920
export const BANK_HOLDER_DOCUMENT = 921
export const BANK_COMPANY_DOCUMENT = 922
export const BANK_NUMBER = 923
export const BANK_AGENCY_NUMBER = 924
export const BANK_TYPE_OF_ACCOUNT = 925
export const COMPANY_NAME = 926
export const COMPANY_CNPJ = 927
export const IMAGES_USER = 928
export const IMAGES_VEHICLE = 929
export const IMAGES_DRIVER_LICENSE = 930

export default {
  EMAIL,
  NAME,
  DATE_OF_BIRTH,
  PERSONAL_DOCUMENT,
  PERSONAL_EMAIL,
  TELEPHONE,
  DRIVER_LICENSE_NUMBER,
  DRIVER_LICENSE_EXPIRY_DATE,
  PREFERENCE_CITY,
  VEHICLE_TYPE,
  VEHICLE_BRAND,
  VEHICLE_MODEL,
  VEHICLE_PLATE,
  VEHICLE_MODEL_YEAR,
  VEHICLE_FABRICATION_YEAR,
  VEHICLE_IDENTIFICATION_NUMBER,
  VEHICLE_NATIONAL_REGISTRATION_NUMBER,
  VEHICLE_DOCUMENT,
  VEHICLE_LAST_LICENCE_YEAR,
  VEHICLE_OWNERSHIP,
  BANK_HOLDER_NAME,
  BANK_HOLDER_DOCUMENT,
  BANK_COMPANY_DOCUMENT,
  BANK_NUMBER,
  BANK_AGENCY_NUMBER,
  BANK_TYPE_OF_ACCOUNT,
  COMPANY_NAME,
  COMPANY_CNPJ,
  IMAGES_USER,
  IMAGES_VEHICLE,
  IMAGES_DRIVER_LICENSE
}
