// TODO: Moquei os números aqui enquanto não temos os trem no banco
const EMAIL = 900
const NAME = 901
const DATE_OF_BIRTH = 902
const PERSONAL_DOCUMENT = 903
const PERSONAL_EMAIL = 904
const TELEPHONE = 905
const DRIVER_LICENSE_NUMBER = 906
const DRIVER_LICENSE_EXPIRY_DATE = 907
const PREFERENCE_CITY = 908
const VEHICLE_TYPE = 909
const VEHICLE_BRAND = 910
const VEHICLE_MODEL = 911
const VEHICLE_PLATE = 912
const VEHICLE_MODEL_YEAR = 913
const VEHICLE_FABRICATION_YEAR = 914
const VEHICLE_IDENTIFICATION_NUMBER = 915
const VEHICLE_NATIONAL_REGISTRATION_NUMBER = 916
const VEHICLE_DOCUMENT = 917
const VEHICLE_LAST_LICENCE_YEAR = 918
const VEHICLE_OWNERSHIP = 919
const BANK_HOLDER_NAME = 920
const BANK_HOLDER_DOCUMENT = 921
const BANK_COMPANY_DOCUMENT = 922
const BANK_NUMBER = 923
const BANK_AGENCY_NUMBER = 924
const BANK_TYPE_OF_ACCOUNT = 925
const COMPANY_NAME = 926
const COMPANY_CNPJ = 927
const IMAGES_USER = 928
const IMAGES_VEHICLE = 929
const IMAGES_DRIVER_LICENSE = 930

module.exports = {
  EMAIL,
  NAME,
  DATE_OF_BIRTH,
  PERSONAL_DOCUMENT,
  PERSONAL_EMAIL,
  TELEPHONE,
  DRIVER_LICENSE_NUMBER,
  DRIVER_LICENSE_EXPIRY_DATE,
  PREFERENCE_CITY,
  VEHICLE_TYPE,
  VEHICLE_BRAND,
  VEHICLE_MODEL,
  VEHICLE_PLATE,
  VEHICLE_MODEL_YEAR,
  VEHICLE_FABRICATION_YEAR,
  VEHICLE_IDENTIFICATION_NUMBER,
  VEHICLE_NATIONAL_REGISTRATION_NUMBER,
  VEHICLE_DOCUMENT,
  VEHICLE_LAST_LICENCE_YEAR,
  VEHICLE_OWNERSHIP,
  BANK_HOLDER_NAME,
  BANK_HOLDER_DOCUMENT,
  BANK_COMPANY_DOCUMENT,
  BANK_NUMBER,
  BANK_AGENCY_NUMBER,
  BANK_TYPE_OF_ACCOUNT,
  COMPANY_NAME,
  COMPANY_CNPJ,
  IMAGES_USER,
  IMAGES_VEHICLE,
  IMAGES_DRIVER_LICENSE
}
