CREATE TABLE `cyezaqab_HCbD`.`courier_user` (
  `courier_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `date_of_birth` DATETIME NULL,
  `personal_document` VARCHAR(255) NULL,
  `personal_email` VARCHAR(255) NULL,
  `telephone` VARCHAR(255) NULL,
  `driver_license_number` VARCHAR(255) NULL,
  `driver_license_expiry_date` DATETIME NULL,
  `preference_city` VARCHAR(255) NULL,
  `vehicle_type` VARCHAR(255) NULL,
  `vehicle_brand` VARCHAR(255) NULL,
  `vehicle_model` VARCHAR(255) NULL,
  `vehicle_plate` VARCHAR(255) NULL,
  `vehicle_model_year` VARCHAR(255) NULL,
  `vehicle_fabrication_year` VARCHAR(255) NULL,
  `vehicle_identification_number` VARCHAR(255) NULL,
  `vehicle_national_registration_number` VARCHAR(255) NULL,
  `vehicle_document` VARCHAR(255) NULL,
  `vehicle_last_licence_year` VARCHAR(255) NULL,
  `vehicle_ownership` VARCHAR(255) NULL,
  `bank_holder_name` VARCHAR(255) NULL,
  `bank_holder_document` VARCHAR(255) NULL,
  `bank_company_document` VARCHAR(255) NULL,
  `bank_number` VARCHAR(255) NULL,
  `bank_agency_number` VARCHAR(255) NULL,
  `bank_acount_number` VARCHAR(255) NULL,
  `bank_type_of_account` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `company_cnpj` VARCHAR(255) NULL,
  `images_user` VARCHAR(255) NULL,
  `images_vehicle` VARCHAR(255) NULL,
  `images_driver_license` VARCHAR(255) NULL,
  PRIMARY KEY (`courier_id`));
